import { VaccinationRecord } from 'src/app/shared/models/vaccination-record.model';

export const MOCK_RECORDS: VaccinationRecord[] = [
  {
    id: 'rec-h-bcg-1',
    childId: 'child-1',
    vaccineId: 'bcg',
    dose: 1,
    scheduledDate: '2024-01-15',
    applicationDate: '2024-01-15',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-hepb-1',
    childId: 'child-1',
    vaccineId: 'hepatite-b',
    dose: 1,
    scheduledDate: '2024-01-15',
    applicationDate: '2024-01-15',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-penta-1',
    childId: 'child-1',
    vaccineId: 'penta',
    dose: 1,
    scheduledDate: '2024-03-15',
    applicationDate: '2024-03-20',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-penta-2',
    childId: 'child-1',
    vaccineId: 'penta',
    dose: 2,
    scheduledDate: '2024-05-15',
    applicationDate: '2024-05-18',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-penta-3',
    childId: 'child-1',
    vaccineId: 'penta',
    dose: 3,
    scheduledDate: '2024-07-15',
    applicationDate: '2024-07-22',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-vip-1',
    childId: 'child-1',
    vaccineId: 'vip',
    dose: 1,
    scheduledDate: '2024-03-15',
    applicationDate: '2024-03-20',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-vip-2',
    childId: 'child-1',
    vaccineId: 'vip',
    dose: 2,
    scheduledDate: '2024-05-15',
    applicationDate: '2024-05-18',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-vip-3',
    childId: 'child-1',
    vaccineId: 'vip',
    dose: 3,
    scheduledDate: '2024-07-15',
    applicationDate: '2024-07-22',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-rota-1',
    childId: 'child-1',
    vaccineId: 'rotavirus',
    dose: 1,
    scheduledDate: '2024-03-15',
    applicationDate: '2024-03-20',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-rota-2',
    childId: 'child-1',
    vaccineId: 'rotavirus',
    dose: 2,
    scheduledDate: '2024-05-15',
    applicationDate: '2024-05-18',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-pneumo-1',
    childId: 'child-1',
    vaccineId: 'pneumo10',
    dose: 1,
    scheduledDate: '2024-03-15',
    applicationDate: '2024-03-20',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-pneumo-2',
    childId: 'child-1',
    vaccineId: 'pneumo10',
    dose: 2,
    scheduledDate: '2024-05-15',
    applicationDate: '2024-05-18',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-pneumo-3',
    childId: 'child-1',
    vaccineId: 'pneumo10',
    dose: 3,
    scheduledDate: '2025-01-15',
    applicationDate: '2025-01-20',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-menc-1',
    childId: 'child-1',
    vaccineId: 'meningo-c',
    dose: 1,
    scheduledDate: '2024-04-15',
    applicationDate: '2024-04-18',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-menc-2',
    childId: 'child-1',
    vaccineId: 'meningo-c',
    dose: 2,
    scheduledDate: '2024-06-15',
    applicationDate: '2024-06-19',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-fa-1',
    childId: 'child-1',
    vaccineId: 'febre-amarela',
    dose: 1,
    scheduledDate: '2024-10-15',
    applicationDate: '2024-10-18',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-tv-1',
    childId: 'child-1',
    vaccineId: 'triplice-viral',
    dose: 1,
    scheduledDate: '2025-01-15',
    applicationDate: '2025-01-20',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-menacwy-1',
    childId: 'child-1',
    vaccineId: 'meningo-acwy',
    dose: 1,
    scheduledDate: '2025-01-15',
    applicationDate: '2025-01-20',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-hepa-1',
    childId: 'child-1',
    vaccineId: 'hepatite-a',
    dose: 1,
    scheduledDate: '2025-04-15',
    applicationDate: '2025-04-22',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-tv-2',
    childId: 'child-1',
    vaccineId: 'triplice-viral',
    dose: 2,
    scheduledDate: '2025-04-15',
    applicationDate: '2025-04-22',
    status: 'applied',
    healthUnit: 'UBS Central',
  },
  {
    id: 'rec-h-vip-4',
    childId: 'child-1',
    vaccineId: 'vip',
    dose: 4,
    scheduledDate: '2025-04-15',
    status: 'overdue',
  },
  {
    id: 'rec-h-dtp-1',
    childId: 'child-1',
    vaccineId: 'dtp',
    dose: 1,
    scheduledDate: '2025-04-15',
    status: 'overdue',
  },
  {
    id: 'rec-h-varicela-1',
    childId: 'child-1',
    vaccineId: 'varicela',
    dose: 1,
    scheduledDate: '2025-04-15',
    status: 'overdue',
  },
  {
    id: 'rec-h-dtp-2',
    childId: 'child-1',
    vaccineId: 'dtp',
    dose: 2,
    scheduledDate: '2028-01-15',
    status: 'pending',
  },
  {
    id: 'rec-m-bcg-1',
    childId: 'child-2',
    vaccineId: 'bcg',
    dose: 1,
    scheduledDate: '2021-09-03',
    applicationDate: '2021-09-03',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-hepb-1',
    childId: 'child-2',
    vaccineId: 'hepatite-b',
    dose: 1,
    scheduledDate: '2021-09-03',
    applicationDate: '2021-09-03',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-penta-1',
    childId: 'child-2',
    vaccineId: 'penta',
    dose: 1,
    scheduledDate: '2021-11-03',
    applicationDate: '2021-11-05',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-penta-2',
    childId: 'child-2',
    vaccineId: 'penta',
    dose: 2,
    scheduledDate: '2022-01-03',
    applicationDate: '2022-01-06',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-penta-3',
    childId: 'child-2',
    vaccineId: 'penta',
    dose: 3,
    scheduledDate: '2022-03-03',
    applicationDate: '2022-03-08',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-vip-1',
    childId: 'child-2',
    vaccineId: 'vip',
    dose: 1,
    scheduledDate: '2021-11-03',
    applicationDate: '2021-11-05',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-vip-2',
    childId: 'child-2',
    vaccineId: 'vip',
    dose: 2,
    scheduledDate: '2022-01-03',
    applicationDate: '2022-01-06',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-vip-3',
    childId: 'child-2',
    vaccineId: 'vip',
    dose: 3,
    scheduledDate: '2022-03-03',
    applicationDate: '2022-03-08',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-pneumo-1',
    childId: 'child-2',
    vaccineId: 'pneumo10',
    dose: 1,
    scheduledDate: '2021-11-03',
    applicationDate: '2021-11-05',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-pneumo-2',
    childId: 'child-2',
    vaccineId: 'pneumo10',
    dose: 2,
    scheduledDate: '2022-01-03',
    applicationDate: '2022-01-06',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-pneumo-3',
    childId: 'child-2',
    vaccineId: 'pneumo10',
    dose: 3,
    scheduledDate: '2022-09-03',
    applicationDate: '2022-09-08',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-fa-1',
    childId: 'child-2',
    vaccineId: 'febre-amarela',
    dose: 1,
    scheduledDate: '2022-06-03',
    applicationDate: '2022-06-07',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-tv-1',
    childId: 'child-2',
    vaccineId: 'triplice-viral',
    dose: 1,
    scheduledDate: '2022-09-03',
    applicationDate: '2022-09-10',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-menacwy-1',
    childId: 'child-2',
    vaccineId: 'meningo-acwy',
    dose: 1,
    scheduledDate: '2022-09-03',
    applicationDate: '2022-09-10',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-tv-2',
    childId: 'child-2',
    vaccineId: 'triplice-viral',
    dose: 2,
    scheduledDate: '2022-12-03',
    applicationDate: '2022-12-07',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-dtp-1',
    childId: 'child-2',
    vaccineId: 'dtp',
    dose: 1,
    scheduledDate: '2022-12-03',
    applicationDate: '2022-12-07',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-varicela-1',
    childId: 'child-2',
    vaccineId: 'varicela',
    dose: 1,
    scheduledDate: '2022-12-03',
    applicationDate: '2022-12-07',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-hepa-1',
    childId: 'child-2',
    vaccineId: 'hepatite-a',
    dose: 1,
    scheduledDate: '2022-12-03',
    applicationDate: '2022-12-07',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-vip-4',
    childId: 'child-2',
    vaccineId: 'vip',
    dose: 4,
    scheduledDate: '2022-12-03',
    applicationDate: '2022-12-07',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-fa-2',
    childId: 'child-2',
    vaccineId: 'febre-amarela',
    dose: 2,
    scheduledDate: '2025-09-03',
    applicationDate: '2025-09-09',
    status: 'applied',
    healthUnit: 'UBS Jardim',
  },
  {
    id: 'rec-m-dtp-2',
    childId: 'child-2',
    vaccineId: 'dtp',
    dose: 2,
    scheduledDate: '2025-09-03',
    status: 'overdue',
  },
  {
    id: 'rec-m-varicela-2',
    childId: 'child-2',
    vaccineId: 'varicela',
    dose: 2,
    scheduledDate: '2025-09-03',
    status: 'overdue',
  },
];
