import { Vaccine } from 'src/app/shared/models/vaccine.model';

export const VACCINE_CALENDAR: Vaccine[] = [
  {
    id: 'bcg',
    name: 'BCG',
    description: 'Protege contra formas graves de tuberculose. Dose única ao nascer.',
    recommendedAgeInMonths: 0,
    recommendedAgesInMonths: [0],
    totalDoses: 1,
  },
  {
    id: 'hepatite-b',
    name: 'Hepatite B',
    description: 'Previne a infecção pelo vírus da hepatite B. Primeira dose ao nascer.',
    recommendedAgeInMonths: 0,
    recommendedAgesInMonths: [0],
    totalDoses: 1,
  },
  {
    id: 'penta',
    name: 'Pentavalente',
    description:
      'Difteria, tétano, coqueluche, hepatite B e Haemophilus influenzae B. Doses aos 2, 4 e 6 meses.',
    recommendedAgeInMonths: 2,
    recommendedAgesInMonths: [2, 4, 6],
    totalDoses: 3,
  },
  {
    id: 'vip',
    name: 'Poliomielite (VIP)',
    description:
      'Protege contra a paralisia infantil. Esquema aos 2, 4 e 6 meses com reforço aos 15 meses.',
    recommendedAgeInMonths: 2,
    recommendedAgesInMonths: [2, 4, 6, 15],
    totalDoses: 4,
  },
  {
    id: 'pneumo10',
    name: 'Pneumocócica 10',
    description:
      'Previne doenças causadas pelo pneumococo, como pneumonia e meningite. Doses aos 2 e 4 meses com reforço aos 12 meses.',
    recommendedAgeInMonths: 2,
    recommendedAgesInMonths: [2, 4, 12],
    totalDoses: 3,
  },
  {
    id: 'rotavirus',
    name: 'Rotavírus',
    description: 'Protege contra a diarreia grave causada pelo rotavírus. Doses aos 2 e 4 meses.',
    recommendedAgeInMonths: 2,
    recommendedAgesInMonths: [2, 4],
    totalDoses: 2,
  },
  {
    id: 'meningo-c',
    name: 'Meningocócica C',
    description: 'Previne a meningite meningocócica do tipo C. Doses aos 3 e 5 meses.',
    recommendedAgeInMonths: 3,
    recommendedAgesInMonths: [3, 5],
    totalDoses: 2,
  },
  {
    id: 'influenza',
    name: 'Influenza (Gripe)',
    description: 'Protege contra a gripe. Vacinação anual a partir dos 6 meses de idade.',
    recommendedAgeInMonths: 6,
    recommendedAgesInMonths: [6],
    totalDoses: 1,
  },
  {
    id: 'febre-amarela',
    name: 'Febre Amarela',
    description: 'Protege contra a febre amarela. Dose aos 9 meses com reforço aos 4 anos.',
    recommendedAgeInMonths: 9,
    recommendedAgesInMonths: [9, 48],
    totalDoses: 2,
  },
  {
    id: 'triplice-viral',
    name: 'Tríplice Viral',
    description: 'Sarampo, caxumba e rubéola. Doses aos 12 e 15 meses.',
    recommendedAgeInMonths: 12,
    recommendedAgesInMonths: [12, 15],
    totalDoses: 2,
  },
  {
    id: 'meningo-acwy',
    name: 'Meningocócica ACWY',
    description:
      'Amplia a proteção contra os meningococos dos tipos A, C, W e Y. Dose aos 12 meses.',
    recommendedAgeInMonths: 12,
    recommendedAgesInMonths: [12],
    totalDoses: 1,
  },
  {
    id: 'dtp',
    name: 'DTP (Tríplice Bacteriana)',
    description:
      'Reforço contra difteria, tétano e coqueluche. Primeiro reforço aos 15 meses e segundo aos 4 anos.',
    recommendedAgeInMonths: 15,
    recommendedAgesInMonths: [15, 48],
    totalDoses: 2,
  },
  {
    id: 'varicela',
    name: 'Varicela (Catapora)',
    description: 'Protege contra a catapora. Dose aos 15 meses com reforço aos 4 anos.',
    recommendedAgeInMonths: 15,
    recommendedAgesInMonths: [15, 48],
    totalDoses: 2,
  },
  {
    id: 'hepatite-a',
    name: 'Hepatite A',
    description: 'Previne a infecção pelo vírus da hepatite A. Dose única aos 15 meses.',
    recommendedAgeInMonths: 15,
    recommendedAgesInMonths: [15],
    totalDoses: 1,
  },
];
